### ISSUE TITLE
Assignment Group: Feature

### ISSUE THREAD

**Issue by hattwj** [OHSU-FM/reindeer#32]
Assignment Group Feature: CRUD, permissions, controller and more
- [ ] #33 Implement Show / Edit views for template
- [ ] #?? Add link to create new group to base Assignments index page
- [ ] #37 Implement permissions (abilities class)
- [ ] #36 Implement controller and create unit tests
- [ ] #8 Ability to crud group comments 
- [ ] #38 Implement behaviors for enable, disabled and never_enabled groups
