### ISSUE TITLE
Assignment Task: Feature

### ISSUE THREAD

**Issue by hattwj** [OHSU-FM/reindeer#44]
## UserAssignment
- [ ] #11 Integration with LimeSurvey
- [ ] #45 Support for Tasks without LimeSurvey
- [ ] #46 Permissions
- [ ] #47 Model 
- [ ] #48 Controller
- [ ] #49 Show / Edit
- [ ] #50 Manager List: progress of many tasks in relation to a single survey
