### ISSUE TITLE
Assignment Template: Feature

### ISSUE THREAD

**Issue by hattwj** [OHSU-FM/reindeer#7]
Assignment Group Templates Feature: CRUD, permissions, controller and more
## Sub Issues
- [ ] #29 Implement Show / Edit views for template
- [ ] #28 Add link to create new template to base Assignments index page
- [ ] #30 Implement template permissions (abilities class)
- [ ] #31 Implement templates controller and create unit tests
## Goal
- [ ] User is able to view a list of templates
- [ ] User is able to delete a template
- [ ] User is able to create a new template
- [ ] User is able to change permission group of template (edit)
- [ ] User is able to add and remove surveys from a template
